export const MapConstants = {
  STATUS:{
    ALERTS:'Alerts',
    MISSED_COMMUNICATION:'MissedCommunication',
    LOW_SIGNAL:'LowSignal',
    LOW_BATTERY:'LowBattery'
  },
  STATUS_NUMBERS:{
    GOOD:'0',
    LOW_SIGNAL:'1',
    LOW_BATTERY:'2',
    MISSED_COMMUNICATION:'3',
    ALERTS:'4'
  },
  SENSOR_TYPE:{
    HUMIDITY:'43',
    CONTACT:'9',
    TEMP:'2'
  }
}
